name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g surge
      - name: Run Surge
        run: surge ./ soft-gun.surge.sh --token ${{secrets.BOOTCAMP_ADVANCED}} 
 
